/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as adminSettingsRouteImport } from './routes/(admin)/settings'
import { Route as adminPollsRouteImport } from './routes/(admin)/polls'
import { Route as adminPagesRouteImport } from './routes/(admin)/pages'
import { Route as adminOverviewRouteImport } from './routes/(admin)/overview'
import { Route as adminModerationRouteImport } from './routes/(admin)/moderation'
import { Route as adminIntegrationsRouteImport } from './routes/(admin)/integrations'
import { Route as adminDomainRouteImport } from './routes/(admin)/domain'
import { Route as adminCustomizeRouteImport } from './routes/(admin)/customize'
import { Route as adminAnalyticsRouteImport } from './routes/(admin)/analytics'
import { Route as adminCommentsIndexRouteImport } from './routes/(admin)/comments/index'
import { Route as adminCommentsCommentIdRouteImport } from './routes/(admin)/comments/$commentId'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingsRoute = adminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPollsRoute = adminPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPagesRoute = adminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminOverviewRoute = adminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminModerationRoute = adminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminIntegrationsRoute = adminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDomainRoute = adminDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminCustomizeRoute = adminCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAnalyticsRoute = adminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminCommentsIndexRoute = adminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminCommentsCommentIdRoute = adminCommentsCommentIdRouteImport.update({
  id: '/comments/$commentId',
  path: '/comments/$commentId',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/widget': typeof WidgetRoute
  '/analytics': typeof adminAnalyticsRoute
  '/customize': typeof adminCustomizeRoute
  '/domain': typeof adminDomainRoute
  '/integrations': typeof adminIntegrationsRoute
  '/moderation': typeof adminModerationRoute
  '/overview': typeof adminOverviewRoute
  '/pages': typeof adminPagesRoute
  '/polls': typeof adminPollsRoute
  '/settings': typeof adminSettingsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/comments/$commentId': typeof adminCommentsCommentIdRoute
  '/comments/': typeof adminCommentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/widget': typeof WidgetRoute
  '/analytics': typeof adminAnalyticsRoute
  '/customize': typeof adminCustomizeRoute
  '/domain': typeof adminDomainRoute
  '/integrations': typeof adminIntegrationsRoute
  '/moderation': typeof adminModerationRoute
  '/overview': typeof adminOverviewRoute
  '/pages': typeof adminPagesRoute
  '/polls': typeof adminPollsRoute
  '/settings': typeof adminSettingsRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/comments/$commentId': typeof adminCommentsCommentIdRoute
  '/comments': typeof adminCommentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/widget': typeof WidgetRoute
  '/(admin)/analytics': typeof adminAnalyticsRoute
  '/(admin)/customize': typeof adminCustomizeRoute
  '/(admin)/domain': typeof adminDomainRoute
  '/(admin)/integrations': typeof adminIntegrationsRoute
  '/(admin)/moderation': typeof adminModerationRoute
  '/(admin)/overview': typeof adminOverviewRoute
  '/(admin)/pages': typeof adminPagesRoute
  '/(admin)/polls': typeof adminPollsRoute
  '/(admin)/settings': typeof adminSettingsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/(admin)/comments/$commentId': typeof adminCommentsCommentIdRoute
  '/(admin)/comments/': typeof adminCommentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/widget'
    | '/analytics'
    | '/customize'
    | '/domain'
    | '/integrations'
    | '/moderation'
    | '/overview'
    | '/pages'
    | '/polls'
    | '/settings'
    | '/onboarding/'
    | '/comments/$commentId'
    | '/comments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/widget'
    | '/analytics'
    | '/customize'
    | '/domain'
    | '/integrations'
    | '/moderation'
    | '/overview'
    | '/pages'
    | '/polls'
    | '/settings'
    | '/onboarding'
    | '/comments/$commentId'
    | '/comments'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/login'
    | '/register'
    | '/widget'
    | '/(admin)/analytics'
    | '/(admin)/customize'
    | '/(admin)/domain'
    | '/(admin)/integrations'
    | '/(admin)/moderation'
    | '/(admin)/overview'
    | '/(admin)/pages'
    | '/(admin)/polls'
    | '/(admin)/settings'
    | '/onboarding/'
    | '/(admin)/comments/$commentId'
    | '/(admin)/comments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WidgetRoute: typeof WidgetRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/settings': {
      id: '/(admin)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminSettingsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/polls': {
      id: '/(admin)/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof adminPollsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/pages': {
      id: '/(admin)/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof adminPagesRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/overview': {
      id: '/(admin)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof adminOverviewRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/moderation': {
      id: '/(admin)/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof adminModerationRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/integrations': {
      id: '/(admin)/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof adminIntegrationsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/domain': {
      id: '/(admin)/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof adminDomainRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/customize': {
      id: '/(admin)/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof adminCustomizeRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/analytics': {
      id: '/(admin)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof adminAnalyticsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/comments/': {
      id: '/(admin)/comments/'
      path: '/comments'
      fullPath: '/comments/'
      preLoaderRoute: typeof adminCommentsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/comments/$commentId': {
      id: '/(admin)/comments/$commentId'
      path: '/comments/$commentId'
      fullPath: '/comments/$commentId'
      preLoaderRoute: typeof adminCommentsCommentIdRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAnalyticsRoute: typeof adminAnalyticsRoute
  adminCustomizeRoute: typeof adminCustomizeRoute
  adminDomainRoute: typeof adminDomainRoute
  adminIntegrationsRoute: typeof adminIntegrationsRoute
  adminModerationRoute: typeof adminModerationRoute
  adminOverviewRoute: typeof adminOverviewRoute
  adminPagesRoute: typeof adminPagesRoute
  adminPollsRoute: typeof adminPollsRoute
  adminSettingsRoute: typeof adminSettingsRoute
  adminCommentsCommentIdRoute: typeof adminCommentsCommentIdRoute
  adminCommentsIndexRoute: typeof adminCommentsIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAnalyticsRoute: adminAnalyticsRoute,
  adminCustomizeRoute: adminCustomizeRoute,
  adminDomainRoute: adminDomainRoute,
  adminIntegrationsRoute: adminIntegrationsRoute,
  adminModerationRoute: adminModerationRoute,
  adminOverviewRoute: adminOverviewRoute,
  adminPagesRoute: adminPagesRoute,
  adminPollsRoute: adminPollsRoute,
  adminSettingsRoute: adminSettingsRoute,
  adminCommentsCommentIdRoute: adminCommentsCommentIdRoute,
  adminCommentsIndexRoute: adminCommentsIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WidgetRoute: WidgetRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
