/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminThemesRouteImport } from './routes/(admin)/themes'
import { Route as adminSettingsRouteImport } from './routes/(admin)/settings'
import { Route as adminPollsRouteImport } from './routes/(admin)/polls'
import { Route as adminPagesRouteImport } from './routes/(admin)/pages'
import { Route as adminOverviewRouteImport } from './routes/(admin)/overview'
import { Route as adminModerationRouteImport } from './routes/(admin)/moderation'
import { Route as adminIntegrationsRouteImport } from './routes/(admin)/integrations'
import { Route as adminDeployRouteImport } from './routes/(admin)/deploy'
import { Route as adminCommentsRouteImport } from './routes/(admin)/comments'
import { Route as adminAnalyticsRouteImport } from './routes/(admin)/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminThemesRoute = adminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminSettingsRoute = adminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPollsRoute = adminPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPagesRoute = adminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminOverviewRoute = adminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminModerationRoute = adminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminIntegrationsRoute = adminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDeployRoute = adminDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminCommentsRoute = adminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAnalyticsRoute = adminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/analytics': typeof adminAnalyticsRoute
  '/comments': typeof adminCommentsRoute
  '/deploy': typeof adminDeployRoute
  '/integrations': typeof adminIntegrationsRoute
  '/moderation': typeof adminModerationRoute
  '/overview': typeof adminOverviewRoute
  '/pages': typeof adminPagesRoute
  '/polls': typeof adminPollsRoute
  '/settings': typeof adminSettingsRoute
  '/themes': typeof adminThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/analytics': typeof adminAnalyticsRoute
  '/comments': typeof adminCommentsRoute
  '/deploy': typeof adminDeployRoute
  '/integrations': typeof adminIntegrationsRoute
  '/moderation': typeof adminModerationRoute
  '/overview': typeof adminOverviewRoute
  '/pages': typeof adminPagesRoute
  '/polls': typeof adminPollsRoute
  '/settings': typeof adminSettingsRoute
  '/themes': typeof adminThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/(admin)/analytics': typeof adminAnalyticsRoute
  '/(admin)/comments': typeof adminCommentsRoute
  '/(admin)/deploy': typeof adminDeployRoute
  '/(admin)/integrations': typeof adminIntegrationsRoute
  '/(admin)/moderation': typeof adminModerationRoute
  '/(admin)/overview': typeof adminOverviewRoute
  '/(admin)/pages': typeof adminPagesRoute
  '/(admin)/polls': typeof adminPollsRoute
  '/(admin)/settings': typeof adminSettingsRoute
  '/(admin)/themes': typeof adminThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/analytics'
    | '/comments'
    | '/deploy'
    | '/integrations'
    | '/moderation'
    | '/overview'
    | '/pages'
    | '/polls'
    | '/settings'
    | '/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/analytics'
    | '/comments'
    | '/deploy'
    | '/integrations'
    | '/moderation'
    | '/overview'
    | '/pages'
    | '/polls'
    | '/settings'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/dashboard'
    | '/login'
    | '/(admin)/analytics'
    | '/(admin)/comments'
    | '/(admin)/deploy'
    | '/(admin)/integrations'
    | '/(admin)/moderation'
    | '/(admin)/overview'
    | '/(admin)/pages'
    | '/(admin)/polls'
    | '/(admin)/settings'
    | '/(admin)/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/themes': {
      id: '/(admin)/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof adminThemesRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/settings': {
      id: '/(admin)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminSettingsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/polls': {
      id: '/(admin)/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof adminPollsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/pages': {
      id: '/(admin)/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof adminPagesRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/overview': {
      id: '/(admin)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof adminOverviewRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/moderation': {
      id: '/(admin)/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof adminModerationRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/integrations': {
      id: '/(admin)/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof adminIntegrationsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/deploy': {
      id: '/(admin)/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof adminDeployRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/comments': {
      id: '/(admin)/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof adminCommentsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/analytics': {
      id: '/(admin)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof adminAnalyticsRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAnalyticsRoute: typeof adminAnalyticsRoute
  adminCommentsRoute: typeof adminCommentsRoute
  adminDeployRoute: typeof adminDeployRoute
  adminIntegrationsRoute: typeof adminIntegrationsRoute
  adminModerationRoute: typeof adminModerationRoute
  adminOverviewRoute: typeof adminOverviewRoute
  adminPagesRoute: typeof adminPagesRoute
  adminPollsRoute: typeof adminPollsRoute
  adminSettingsRoute: typeof adminSettingsRoute
  adminThemesRoute: typeof adminThemesRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAnalyticsRoute: adminAnalyticsRoute,
  adminCommentsRoute: adminCommentsRoute,
  adminDeployRoute: adminDeployRoute,
  adminIntegrationsRoute: adminIntegrationsRoute,
  adminModerationRoute: adminModerationRoute,
  adminOverviewRoute: adminOverviewRoute,
  adminPagesRoute: adminPagesRoute,
  adminPollsRoute: adminPollsRoute,
  adminSettingsRoute: adminSettingsRoute,
  adminThemesRoute: adminThemesRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
